name: Docker Build & Deploy for EC2

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    name: docker build and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Import PGP(gpg) credentials
        run: |
          echo -e "$PGP_PRIVATE_KEY" | gpg --import
        env:
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}

      - name: Ckeck GPG Key
        run: |
          gpg --version
          gpg --list-key song22861@naver.com

      - name: Install sops
        env:
          SOPS_VERSION: v3.7.1
        run: |
          wget https://github.com/mozilla/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux
          chmod +x ./sops-${SOPS_VERSION}.linux
          sudo mv ./sops-${SOPS_VERSION}.linux /usr/local/bin/sops

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Generate Pem
        env:
          PEM: ${{ secrets.SSH_PEM_KEY }}
        run: |
          echo -e "$PEM" > hello-aws-docker.pem
          chmod 400 hello-aws-docker.pem

      - name: Docker build and push image to Amazon ECR and Development Deploy
        env:
          ECR: ${{ steps.login-ecr.outputs.registry }}
          TAG: ${{ github.sha }}
          PEM: ${{ secrets.SSH_PEM_KEY }}
        run: |
          echo "== build ========================================================"
          docker build --build-arg NODE_ENV=development -t ${ECR}/hello-aws-docker:development -t ${ECR}/hello-aws-docker:development-${TAG} .
          echo "== push ========================================================="
          docker push ${ECR}/hello-aws-docker --all-tags
          bash ./deploy.sh development
